// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmcgxjmkvqfyvsfsiexe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtY2d4am1rdnFmeXZzZnNpZXhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTQ5NDUsImV4cCI6MjA2NDQ3MDk0NX0.9J_QQMQjdmdKzIPyvcyVqMsP6WBZA2RneZi7pXGSbOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);